export default {
  size: 'sm',
  sizes: [
    { label: 'Small', value: 'sm' },
    { label: 'Medium', value: 'md' },
    { label: 'Large', value: 'lg' },
  ],
  color: 10,
  colors: [
    /*
    {
      id: 1,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#16a085',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 2,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#27ae60',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 3,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#2980b9',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 4,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#8e44ad',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 5,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#2c3e50',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 6,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#f39c12',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 7,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#d35400',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 8,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#c0392b',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 9,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#7f8c8d',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    */
    {
      id: 10,
      backgroundColor1: '#1abc9c',
      backgroundColor2: '#16a085',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 11,
      backgroundColor1: '#2ecc71',
      backgroundColor2: '#27ae60',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 12,
      backgroundColor1: '#3498db',
      backgroundColor2: '#2980b9',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 13,
      backgroundColor1: '#9b59b6',
      backgroundColor2: '#8e44ad',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 14,
      backgroundColor1: '#34495e',
      backgroundColor2: '#2c3e50',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 15,
      backgroundColor1: '#f1c40f',
      backgroundColor2: '#f39c12',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 16,
      backgroundColor1: '#e67e22',
      backgroundColor2: '#d35400',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 17,
      backgroundColor1: '#e74c3c',
      backgroundColor2: '#c0392b',
      textColor1: '#fff',
      textColor2: '#fff',
    },
    {
      id: 9,
      backgroundColor1: '#a7bfc1',
      backgroundColor2: '#7f8c8d',
      textColor1: '#fff',
      textColor2: '#fff',
    },
  ],
  text1: 'foo',
  text2: 'bar',
};
